apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test-deployment
  labels:
    app: k8-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-test
  template:
    metadata:
      labels:
        app: k8-test 
    spec:
      containers:
      - name: nodeserver
        image: betawfeek/k8-test/k8-test:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: k8-test-service
spec:
  selector:
    app: k8-test 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110